// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53I9l_zj3-rKOhViQquzJbV-X246rANk',
    appId: '1:14032643904:web:fc4a927e23df38d8553ca5',
    messagingSenderId: '14032643904',
    projectId: 'weshall-71da6',
    authDomain: 'weshall-71da6.firebaseapp.com',
    storageBucket: 'weshall-71da6.appspot.com',
    measurementId: 'G-TBW9TR068D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZqD_ujF_vbR_Sucw1n-ddDwIkbH5xVHA',
    appId: '1:14032643904:android:2e83d9123643bf7e553ca5',
    messagingSenderId: '14032643904',
    projectId: 'weshall-71da6',
    storageBucket: 'weshall-71da6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZdpNsTc-pD02huhUVt5MKq20Q-pQmBlo',
    appId: '1:14032643904:ios:f38fd92c62749f50553ca5',
    messagingSenderId: '14032643904',
    projectId: 'weshall-71da6',
    storageBucket: 'weshall-71da6.appspot.com',
    iosClientId: '14032643904-r43f1jh4n6un33941ivntdmaabgpvp0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.weshallsah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZdpNsTc-pD02huhUVt5MKq20Q-pQmBlo',
    appId: '1:14032643904:ios:e116296c9c8ac377553ca5',
    messagingSenderId: '14032643904',
    projectId: 'weshall-71da6',
    storageBucket: 'weshall-71da6.appspot.com',
    iosClientId: '14032643904-te1anog77c8st4aucrti9ustneoakhed.apps.googleusercontent.com',
    iosBundleId: 'com.example.weshallsah.RunnerTests',
  );
}
